// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/cart/": {
            "get": {
                "security": [
                    {
                        "AuthBearer": []
                    }
                ],
                "description": "Get Cart Detail",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Get Cart",
                "responses": {
                    "200": {
                        "description": "Cart Response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CartResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AuthBearer": []
                    }
                ],
                "description": "Add Product to Cart",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Add Product to Cart",
                "parameters": [
                    {
                        "description": "Add Product to Cart",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CartItemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Product response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CartResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "AuthBearer": []
                    }
                ],
                "description": "Remove From Cart",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Cart"
                ],
                "summary": "Remove From Cart",
                "parameters": [
                    {
                        "description": "Remove Product to Cart",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CartItemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Product response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CartResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/categories/": {
            "post": {
                "description": "Create a Category",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Create a Category",
                "parameters": [
                    {
                        "description": "Create a Category",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CreateUpdateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Category response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CategoryResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/categories/get-by-filter": {
            "post": {
                "description": "Get a Category",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Get a Category",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.PaginationInputWithFilter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Category response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.PagedList-github_com_wahid-wex_e-commerce-backend_api_dto_CategoryResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/categories/{id}": {
            "get": {
                "description": "Get a Category",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Get a Category",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Category response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CategoryResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a Category",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Update a Category",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update a Category",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CreateUpdateCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Category response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CategoryResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a Category",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Delete a Category",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/order/": {
            "post": {
                "security": [
                    {
                        "AuthBearer": []
                    }
                ],
                "description": "Finalize Order",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Finalize Order",
                "parameters": [
                    {
                        "description": "Finalize Order",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CheckoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CheckoutResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/products/": {
            "post": {
                "security": [
                    {
                        "AuthBearer": []
                    }
                ],
                "description": "Create a Product",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Create a Product",
                "parameters": [
                    {
                        "description": "Create a Product",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CreateUpdateProductRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Product response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.ProductResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/products/change-stock": {
            "post": {
                "security": [
                    {
                        "AuthBearer": []
                    }
                ],
                "description": "Change or create stock of product",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Change Stock",
                "parameters": [
                    {
                        "description": "Stock Change",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CreateUpdateProductStockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Stock response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/products/favorite": {
            "post": {
                "security": [
                    {
                        "AuthBearer": []
                    }
                ],
                "description": "Add a product to customer's favorites",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Add a product to favorites",
                "parameters": [
                    {
                        "description": "Add to favorites request",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.AddRemoveToFavoriteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Favorite response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.FavoriteResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "AuthBearer": []
                    }
                ],
                "description": "remove a product from customer's favorites",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "remove a product from favorites",
                "parameters": [
                    {
                        "description": "Add to favorites request",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.AddRemoveToFavoriteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Favorite response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.FavoriteResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/products/get-by-filter": {
            "post": {
                "security": [
                    {
                        "AuthBearer": []
                    }
                ],
                "description": "Get a Product",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Get a Product",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.PaginationInputWithFilter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.PagedList-github_com_wahid-wex_e-commerce-backend_api_dto_ProductResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/products/leave-review": {
            "post": {
                "security": [
                    {
                        "AuthBearer": []
                    }
                ],
                "description": "Add a product to customer's favorites",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Add a product to favorites",
                "parameters": [
                    {
                        "description": "Add to favorites request",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CreateReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Favorite response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "type": "object"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/products/{id}": {
            "get": {
                "security": [
                    {
                        "AuthBearer": []
                    }
                ],
                "description": "Get a Product",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Get a Product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.ProductResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "AuthBearer": []
                    }
                ],
                "description": "Update a Product",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Update a Product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update a Product",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CreateUpdateProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Product response",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.ProductResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "AuthBearer": []
                    }
                ],
                "description": "Delete a Product",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Delete a Product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/login-customer-by-mobile": {
            "post": {
                "description": "RegisterLoginCustomerByMobileNumber",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "RegisterLoginCustomerByMobileNumber",
                "parameters": [
                    {
                        "description": "RegisterLoginByMobileRequest",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.RegisterLoginByMobileRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "400": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "409": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/login-customer-by-username": {
            "post": {
                "description": "LoginCustomerByUsername",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "LoginCustomerByUsername",
                "parameters": [
                    {
                        "description": "LoginByUsernameRequest",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.LoginByUsernameRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "400": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "409": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/login-seller-by-mobile": {
            "post": {
                "description": "RegisterLoginSellerByMobileNumber",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "RegisterLoginSellerByMobileNumber",
                "parameters": [
                    {
                        "description": "RegisterLoginByMobileRequest",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.RegisterLoginByMobileRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "400": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "409": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/login-seller-by-username": {
            "post": {
                "description": "LoginSellerByUsername",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "LoginSellerByUsername",
                "parameters": [
                    {
                        "description": "LoginByUsernameRequest",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.LoginByUsernameRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "400": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "409": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/refresh-customer-token": {
            "post": {
                "description": "Send RefreshToken and Then get new token credential",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Refresh",
                "parameters": [
                    {
                        "description": "RefreshTokenRequest",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "400": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "409": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/refresh-seller-token": {
            "post": {
                "description": "Send RefreshToken and Then get new token credential",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Refresh",
                "parameters": [
                    {
                        "description": "RefreshTokenRequest",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "400": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "409": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/register-customer-by-username": {
            "post": {
                "description": "RegisterCustomerByUsername",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "RegisterCustomerByUsername",
                "parameters": [
                    {
                        "description": "RegisterCustomerByUsernameRequest",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.RegisterCustomerByUsernameRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "400": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "409": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/register-seller-by-username": {
            "post": {
                "description": "RegisterSellerByUsername",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "RegisterSellerByUsername",
                "parameters": [
                    {
                        "description": "RegisterSellerByUsernameRequest",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.RegisterSellerByUsernameRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "400": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "409": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/send-customer-otp": {
            "post": {
                "description": "Send otp to user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Send otp to user",
                "parameters": [
                    {
                        "description": "GetOtpRequest",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.GetOtpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "400": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "409": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        },
        "/v1/users/send-seller-otp": {
            "post": {
                "description": "Send otp to user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Send otp to user",
                "parameters": [
                    {
                        "description": "GetOtpRequest",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.GetOtpRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "400": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    },
                    "409": {
                        "description": "Failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_wahid-wex_e-commerce-backend_api_dto.AddRemoveToFavoriteRequest": {
            "type": "object",
            "required": [
                "product_id"
            ],
            "properties": {
                "product_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.CartItemRequest": {
            "type": "object",
            "required": [
                "product_id"
            ],
            "properties": {
                "product_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.CartItemResponse": {
            "type": "object",
            "properties": {
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "productId": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.CartResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CartItemResponse"
                    }
                },
                "totalPrice": {
                    "type": "number"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.CategoryResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imageUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.CheckoutRequest": {
            "type": "object",
            "required": [
                "shippingAddress"
            ],
            "properties": {
                "shippingAddress": {
                    "type": "string"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.CheckoutResponse": {
            "type": "object",
            "required": [
                "paymentGatewayUrl"
            ],
            "properties": {
                "paymentGatewayUrl": {
                    "type": "string"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.CreateReviewRequest": {
            "type": "object",
            "required": [
                "content",
                "product-id"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 1000,
                    "minLength": 1
                },
                "product-id": {
                    "type": "integer"
                },
                "rating": {
                    "type": "integer"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.CreateUpdateCategoryRequest": {
            "type": "object",
            "required": [
                "description",
                "imageUrl",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 300,
                    "minLength": 10
                },
                "imageUrl": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                },
                "name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.CreateUpdateProductRequest": {
            "type": "object",
            "required": [
                "category_id",
                "name",
                "price"
            ],
            "properties": {
                "attributes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.ProductAttributeDTO"
                    }
                },
                "category_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1
                },
                "price": {
                    "type": "number"
                },
                "stocks": {
                    "type": "integer"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.CreateUpdateProductStockRequest": {
            "type": "object",
            "required": [
                "productId",
                "quantity"
            ],
            "properties": {
                "productId": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.FavoriteResponse": {
            "type": "object",
            "properties": {
                "customerId": {
                    "type": "integer"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.Filter": {
            "type": "object",
            "properties": {
                "filterType": {
                    "description": "text number",
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.GetOtpRequest": {
            "type": "object",
            "required": [
                "mobileNumber"
            ],
            "properties": {
                "mobileNumber": {
                    "type": "string",
                    "maxLength": 11,
                    "minLength": 11
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.LoginByUsernameRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string",
                    "minLength": 5
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.PagedList-github_com_wahid-wex_e-commerce-backend_api_dto_CategoryResponse": {
            "type": "object",
            "properties": {
                "hasNextPage": {
                    "type": "boolean"
                },
                "hasPreviousPage": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CategoryResponse"
                    }
                },
                "pageNumber": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                },
                "totalRows": {
                    "type": "integer"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.PagedList-github_com_wahid-wex_e-commerce-backend_api_dto_ProductResponse": {
            "type": "object",
            "properties": {
                "hasNextPage": {
                    "type": "boolean"
                },
                "hasPreviousPage": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.ProductResponse"
                    }
                },
                "pageNumber": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                },
                "totalRows": {
                    "type": "integer"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.PaginationInputWithFilter": {
            "type": "object",
            "properties": {
                "filter": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.Filter"
                    }
                },
                "pageNumber": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "sort": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.Sort"
                    }
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.ProductAttributeDTO": {
            "type": "object",
            "required": [
                "key",
                "value"
            ],
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.ProductAttributeResponse": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.ProductResponse": {
            "type": "object",
            "properties": {
                "cartItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CartItemResponse"
                    }
                },
                "category": {
                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.CategoryResponse"
                },
                "description": {
                    "type": "string"
                },
                "imageUrl": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "isFavorite": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "productAttributes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.ProductAttributeResponse"
                    }
                },
                "productStocks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.ProductStockResponse"
                    }
                },
                "reviews": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_dto.ReviewResponse"
                    }
                },
                "satisfactionRate": {
                    "type": "number"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.ProductStockResponse": {
            "type": "object",
            "properties": {
                "quantity": {
                    "type": "integer"
                },
                "sellerId": {
                    "type": "integer"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.RegisterCustomerByUsernameRequest": {
            "type": "object",
            "required": [
                "cardNumber",
                "firstName",
                "lastName",
                "password",
                "phone",
                "postalCode",
                "shippingAddress",
                "username"
            ],
            "properties": {
                "cardNumber": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "minLength": 6
                },
                "firstName": {
                    "type": "string",
                    "minLength": 3
                },
                "lastName": {
                    "type": "string",
                    "minLength": 3
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "phone": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "shippingAddress": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "minLength": 5
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.RegisterLoginByMobileRequest": {
            "type": "object",
            "required": [
                "mobileNumber",
                "otp"
            ],
            "properties": {
                "mobileNumber": {
                    "type": "string",
                    "maxLength": 11,
                    "minLength": 11
                },
                "otp": {
                    "type": "string",
                    "maxLength": 6,
                    "minLength": 6
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.RegisterSellerByUsernameRequest": {
            "type": "object",
            "required": [
                "address",
                "nationalId",
                "password",
                "phone",
                "storeName",
                "username"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "minLength": 5
                },
                "description": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "minLength": 6
                },
                "logo": {
                    "type": "string"
                },
                "nationalId": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "phone": {
                    "type": "string",
                    "minLength": 5
                },
                "storeName": {
                    "type": "string",
                    "minLength": 3
                },
                "username": {
                    "type": "string",
                    "minLength": 5
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.ReviewResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "customerId": {
                    "type": "integer"
                },
                "rating": {
                    "type": "integer"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_dto.Sort": {
            "type": "object",
            "properties": {
                "colId": {
                    "type": "string"
                },
                "sort": {
                    "type": "string"
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_helper.BaseHttpResponse": {
            "type": "object",
            "properties": {
                "error": {},
                "result": {},
                "resultCode": {
                    "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_helper.ResultCode"
                },
                "success": {
                    "type": "boolean"
                },
                "validationErrors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_wahid-wex_e-commerce-backend_api_validation.ValidationError"
                    }
                }
            }
        },
        "github_com_wahid-wex_e-commerce-backend_api_helper.ResultCode": {
            "type": "integer",
            "enum": [
                0,
                40001,
                40101,
                40301,
                42901,
                50001,
                50002
            ],
            "x-enum-varnames": [
                "Success",
                "ValidationError",
                "AuthError",
                "ForbiddenError",
                "LimiterError",
                "CustomRecovery",
                "InternalError"
            ]
        },
        "github_com_wahid-wex_e-commerce-backend_api_validation.ValidationError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "property": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "AuthBearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
